receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318


processors:
  batch: null

exporters:

  debug:
    verbosity: detailed

  kafka/logs:
    brokers:
      - 'localhost:9092'
    encoding: otlp_json
    protocol_version: 3.7.0
    topic: apmlogs

  kafka/metrics:
    brokers:
      - 'localhost:9092'
    encoding: otlp_json
    protocol_version: 3.7.0
    topic: apmmetrics

  kafka/traces:
    brokers:
      - 'localhost:9092'
    encoding: otlp_json
    protocol_version: 3.7.0
    topic: apmtraces


service:
  pipelines:

    logs:
      exporters: [debug, kafka/logs]
      processors: [batch]
      receivers: [otlp]

    traces:
      exporters: [debug, kafka/traces]
      processors: [batch]
      receivers: [otlp]

    metrics:
      exporters: [debug, kafka/metrics]
      processors: [batch]
      receivers: [otlp]